include $(TOPDIR)/rules.mk

PKG_VERSION=0.1
PKG_RELEASE:=1

LUCI_TITLE:=Windows/Office Acitvation - vlmcsd
LUCI_DEPENDS:=@((PACKAGE_vlmcsd))
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
