#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-dnscrypt-proxy ) && rm -f /etc/uci-defaults/luci-dnscrypt-proxy
	chmod 755 /etc/init.d/dnscrypt-proxy >/dev/null 2>&1
	/etc/init.d/dnscrypt-proxy enable >/dev/null 2>&1
	exit 0
}
