#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-dns2socks ) && rm -f /etc/uci-defaults/luci-dns2socks
	chmod 755 /etc/init.d/dns2socks >/dev/null 2>&1
	/etc/init.d/dns2socks enable >/dev/null 2>&1
	exit 0
}
