#!/bin/sh 

[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-nwan ) && rm -f /etc/uci-defaults/luci-nwan
	chmod 755 /etc/init.d/nwan >/dev/null 2>&1
	chmod 755 /etc/init.d/nwannumset >/dev/null 2>&1
   /etc/init.d/nwan enable >/dev/null 2>&1
   /etc/init.d/nwannumset enable  >/dev/null 2>&1	
	exit 0
}