#!/bin/sh /etc/rc.common

START=90
STOP=15
PIDFILE='/tmp/run/chinadns.pid'

start()
{
	config_load "chinadns"
	local enabled dns port delay
	config_get enabled config enabled
	config_get dns config dns
	config_get port config port
	config_get delay config delay
	config_get dnscpm config dnscpm

	[ $enabled = '0' ] && exit 0

	if [ -f $PIDFILE ];then
		echo "already started: $PIDFILE exists"
		return 1
	fi

	[ $dnscpm = '0' ] && {
		chinadns \
			-l /etc/chinadns_iplist.txt \
			-c /etc/chinadns_chnroute.txt \
			-d \
			-s "$dns" \
			-y$delay \
			-b 0.0.0.0 \
			-p $port & 
		echo $! > $PIDFILE
	}
	[ $dnscpm = '1' ] && {
		chinadns \
			-l /etc/chinadns_iplist.txt \
			-c /etc/chinadns_chnroute.txt \
			-d \
			-s "$dns" &
			-b 0.0.0.0 \
			-p $port \
			-z &
		echo $! > $PIDFILE
	}

	uci del dhcp.@dnsmasq[-1].server
	uci set dhcp.@dnsmasq[-1].noresolv=1
	uci add_list dhcp.@dnsmasq[-1].server=127.0.0.1#$port
	uci commit dhcp
	/etc/init.d/dnsmasq restart
}

stop()
{
	[ -f $PIDFILE ] && {
		kill -9 `cat $PIDFILE`
		rm $PIDFILE
	}
}
