#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Shadowsocks-libev-spec
LUCI_DEPENDS:=+shadowsocks-libev-ra-spec +kmod-ipt-nat-extra +ip +ipset +iptables-mod-tproxy

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
