#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-n2n ) && rm -f /etc/uci-defaults/luci-n2n
	chmod 755 /etc/init.d/n2n >/dev/null 2>&1
	/etc/init.d/n2n enable >/dev/null 2>&1
	exit 0
}
