#!/bin/sh 

[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-qosv4 ) && rm -f /etc/uci-defaults/luci-qosv4
	chmod 755 /etc/init.d/qosv4  >/dev/null 2>&1
/etc/init.d/qosv4 enable  >/dev/null 2>&1	
sed -i -e '/qos_scheduler/d' /etc/crontabs/root >/dev/null 2>&1	
	exit 0
}