#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-drcom ) && rm -f /etc/uci-defaults/luci-drcom
	chmod 755 /etc/init.d/drcom >/dev/null 2>&1
	/etc/init.d/drcom enable >/dev/null 2>&1
	exit 0
}
