#!/bin/sh 

[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/mentohust ) && rm -f /etc/uci-defaults/mentohust
	chmod 755 /etc/init.d/mentohust >/dev/null 2>&1
   /etc/init.d/mentohust enable >/dev/null 2>&1

	exit 0
}
