#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@wifidog[-1]
	add ucitrack wifidog
	set ucitrack.wifidog="wifidog"
	set ucitrack.wifidog.init='wifidog'
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
